# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MyApp < Formula
  desc ""
  homepage "https://github.com/Noush-012/my-app"
  version "1.0.1"

  on_macos do
    url "https://github.com/Noush-012/my-app/releases/download/v1.0.1/my-app_1.0.1_darwin_all.tar.gz"
    sha256 "f4a978d54d61df899310ee20f00bd5a3ec47f504fc69f822b327d52ae7cb3988"

    def install
      bin.install "my-app"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Noush-012/my-app/releases/download/v1.0.1/my-app_1.0.1_linux_arm64.tar.gz"
      sha256 "0028143550961f1fe07d38c66cf9ae3f10c95653d8f72e1023695aa4bb69ee84"

      def install
        bin.install "my-app"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Noush-012/my-app/releases/download/v1.0.1/my-app_1.0.1_linux_amd64.tar.gz"
      sha256 "21778d68788f6386856bd780715ea147040bcc91ab15c8c3aee82611d7f17c66"

      def install
        bin.install "my-app"
      end
    end
  end
end
